import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DeleteCommand, DynamoDBDocumentClient, GetCommand, PutCommand, ScanCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';
import { identityFromRequest, getProfile } from './server-profile';
const region=process.env.AWS_REGION||process.env.NEXT_PUBLIC_AWS_REGION||'eu-west-3';const tableName=process.env.FIRERANKY_FIRES_TABLE||'fireranky-fires-dev';const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({region}),{marshallOptions:{removeUndefinedValues:true}});
export type FireApplication={fireId:string;repId:string;opportunityId:string;companyId:string;status:string;createdAt:string;updatedAt:string;companyContactedAt?:string;repNudgedAt?:string;repSnapshot:{firstName?:string;lastName?:string;country?:string;city?:string;phone?:string;yearsExperience?:number;industries?:string[];linkedinUrl?:string;bio?:string}};
const COMPANY_BY_OPPORTUNITY:Record<string,string>={'northstar-ai':'northstar-ai-demo','vantagrid':'vantagrid-demo','pulsecare':'pulsecare-demo'};
export async function fireIdentity(request:Request){const identity=await identityFromRequest(request);if(identity.role!=='sales')throw new Error('Only sales reps can fire on opportunities.');const profile=await getProfile(identity.userId);if(!profile?.profileComplete)throw new Error('Complete your sales profile before firing.');if(!profile.phone)throw new Error('Add your phone number before firing.');return{identity,profile};}
export async function getFire(repId:string,opportunityId:string){const fireId=`${repId}#${opportunityId}`;const result=await ddb.send(new GetCommand({TableName:tableName,Key:{fireId},ConsistentRead:true}));return(result.Item as FireApplication|undefined)||null;}
export async function listRepFires(repId:string){const result=await ddb.send(new ScanCommand({TableName:tableName,FilterExpression:'repId = :repId',ExpressionAttributeValues:{':repId':repId}}));return((result.Items||[]) as FireApplication[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export async function createFire(request:Request,opportunityId:string){const{identity,profile}=await fireIdentity(request);const fireId=`${identity.userId}#${opportunityId}`;const existing=await getFire(identity.userId,opportunityId);if(existing)return existing;const now=new Date().toISOString();const fire:FireApplication={fireId,repId:identity.userId,opportunityId,companyId:COMPANY_BY_OPPORTUNITY[opportunityId]||'demo-company',status:'PENDING',createdAt:now,updatedAt:now,repSnapshot:{firstName:profile.firstName,lastName:profile.lastName,country:profile.country,city:profile.city,phone:profile.phone,yearsExperience:profile.yearsExperience,industries:profile.industries,linkedinUrl:profile.linkedinUrl,bio:profile.bio}};await ddb.send(new PutCommand({TableName:tableName,Item:fire,ConditionExpression:'attribute_not_exists(fireId)'}));const persisted=await getFire(identity.userId,opportunityId);if(!persisted)throw new Error('Fire was not persisted.');return persisted;}
export async function acceptCallRequest(request:Request,opportunityId:string){const{identity}=await fireIdentity(request);const fireId=`${identity.userId}#${opportunityId}`;const current=await getFire(identity.userId,opportunityId);if(!current)throw new Error('No fire found for this opportunity.');if(current.status!=='CALL_REQUESTED')throw new Error('There is no pending call request to accept.');const now=new Date().toISOString();const result=await ddb.send(new UpdateCommand({TableName:tableName,Key:{fireId},UpdateExpression:'SET #s=:s, updatedAt=:u, callAcceptedAt=:u',ExpressionAttributeNames:{'#s':'status'},ExpressionAttributeValues:{':s':'CALL_ACCEPTED',':u':now},ReturnValues:'ALL_NEW'}));return result.Attributes as FireApplication;}
export async function nudgeCompany(request:Request,opportunityId:string){const{identity}=await fireIdentity(request),fireId=`${identity.userId}#${opportunityId}`,current=await getFire(identity.userId,opportunityId);if(!current||current.status!=='CALL_ACCEPTED')throw new Error('Follow-up is only available after accepting a call request.');if(current.companyContactedAt)throw new Error('The company has already marked you as contacted.');const now=new Date().toISOString();const result=await ddb.send(new UpdateCommand({TableName:tableName,Key:{fireId},UpdateExpression:'SET repNudgedAt=:u, updatedAt=:u',ExpressionAttributeValues:{':u':now},ReturnValues:'ALL_NEW'}));return result.Attributes as FireApplication;}
export async function leaveFire(request:Request,opportunityId:string){const{identity}=await fireIdentity(request);const fireId=`${identity.userId}#${opportunityId}`;await ddb.send(new DeleteCommand({TableName:tableName,Key:{fireId}}));return{ok:true};}
