'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, Check, Clock3, Flame, Loader2, LogOut, Pencil, Save, Trophy, UserRound } from 'lucide-react';
import { getCurrentUser, getIdToken, type FireRankyUser } from '../lib/auth';

const INDUSTRIES=['SaaS','AI','Healthcare','Cybersecurity','Finance','Agencies','Ecommerce','Consulting','Real Estate','HR Tech','Marketing'];
const NAMES:Record<string,{company:string;title:string}>={
  'northstar-ai':{company:'Northstar AI',title:'AI support platform for fast-growing ecommerce brands.'},
  'vantagrid':{company:'VantaGrid',title:'Enterprise attack-surface monitoring for lean security teams.'},
  'pulsecare':{company:'PulseCare',title:'Patient engagement software for independent medical practices.'},
};
type Fire={fireId:string;opportunityId:string;status:string;createdAt:string};
type Profile={firstName?:string;lastName?:string;country?:string;city?:string;linkedinUrl?:string;yearsExperience?:number;industries?:string[];bio?:string;profileComplete?:boolean};
type Tab='ranking'|'info'|'deals';

export default function AccountPage(){
  const[user,setUser]=useState<FireRankyUser|null>(null);const[profile,setProfile]=useState<Profile>({industries:[]});const[fires,setFires]=useState<Fire[]>([]);const[tab,setTab]=useState<Tab>('ranking');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[editing,setEditing]=useState(false);const[confirm,setConfirm]=useState<string|null>(null);const[leaving,setLeaving]=useState<string|null>(null);const[message,setMessage]=useState('');
  useEffect(()=>{const hash=location.hash.replace('#','') as Tab;if(['ranking','info','deals'].includes(hash))setTab(hash);(async()=>{const current=await getCurrentUser();if(!current){location.href='/';return}if(current.role!=='sales'){location.href='/';return}setUser(current);const token=await getIdToken();const[pRes,fRes]=await Promise.all([fetch('/api/profile',{headers:{Authorization:`Bearer ${token}`}}),fetch('/api/fires',{headers:{Authorization:`Bearer ${token}`}})]);if(pRes.ok){const p=await pRes.json();setProfile({...p.profile,industries:p.profile.industries||[]})}if(fRes.ok){const f=await fRes.json();setFires(f.fires||[])}setLoading(false)})()},[]);
  const stats=useMemo(()=>{const pending=fires.filter(f=>f.status==='PENDING').length;const accepted=fires.filter(f=>f.status==='ACCEPTED').length;const declined=fires.filter(f=>f.status==='DECLINED').length;const xp=fires.length*120+accepted*500;const strength=[profile.firstName,profile.lastName,profile.country,profile.city,profile.yearsExperience,(profile.industries||[]).length,profile.linkedinUrl,profile.bio].filter(Boolean).length;return{pending,accepted,declined,xp,strength:Math.round(strength/8*100),rate:accepted+declined?Math.round(accepted/(accepted+declined)*100):null}},[fires,profile]);
  function go(next:Tab){setTab(next);history.replaceState(null,'',`#${next}`)}
  function set<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>({...p,[key]:value}))}
  function toggle(ind:string){const next=new Set(profile.industries||[]);next.has(ind)?next.delete(ind):next.add(ind);set('industries',Array.from(next).slice(0,5))}
  async function save(){setSaving(true);setMessage('');try{const token=await getIdToken();const res=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(profile)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Unable to save');setProfile(body.profile);setEditing(false);setMessage('Profile updated.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
  async function leave(id:string){setLeaving(id);const token=await getIdToken();const res=await fetch(`/api/fires/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(res.ok)setFires(v=>v.filter(f=>f.opportunityId!==id));setLeaving(null);setConfirm(null)}
  if(loading)return <main className="accountPage"><div className="onboardLoading"><Loader2 className="spin"/> Loading your account…</div></main>;
  if(!user)return null;
  return <main className="accountPage"><div className="accountShell"><a href="/" className="detailBack"><ArrowLeft size={16}/> Back to marketplace</a><header className="accountHero"><div className="accountIdentity"><div className="accountAvatar">{(profile.firstName?.[0]||'J')}{(profile.lastName?.[0]||'M')}</div><div><div className="kicker"><Flame size={14}/> SALES REP</div><h1>{profile.firstName||'Sales'} {profile.lastName||'Rep'}</h1><p>{profile.city&&profile.country?`${profile.city}, ${profile.country} · `:''}{profile.yearsExperience||0} years in sales</p></div></div><div className="accountQuick"><span><strong>{fires.length}</strong><small>active fires</small></span><span><strong>{stats.xp}</strong><small>FireRanky XP</small></span></div></header>
  <nav className="accountTabs"><button className={tab==='ranking'?'active':''} onClick={()=>go('ranking')}><Trophy size={16}/> Ranking</button><button className={tab==='info'?'active':''} onClick={()=>go('info')}><UserRound size={16}/> My info</button><button className={tab==='deals'?'active':''} onClick={()=>go('deals')}><BriefcaseBusiness size={16}/> My deals <span>{fires.length}</span></button></nav>
  {tab==='ranking'&&<section className="accountPanel"><div className="rankingTop"><div><div className="kicker"><Trophy size={14}/> YOUR RANKING</div><h2>{stats.accepted?'Ranking unlocks with verified sales':'Unranked. For now.'}</h2><p>Get an accepted campaign and start closing verified revenue to enter the leaderboard.</p></div><div className="rankOrb"><small>CURRENT RANK</small><strong>—</strong><span>Season 01</span></div></div><div className="statGrid"><article><BarChart3/><small>FIRERANKY XP</small><strong>{stats.xp}</strong><span>+120 per fire · +500 accepted</span></article><article><Flame/><small>ACTIVE FIRES</small><strong>{fires.length}</strong><span>{stats.pending} awaiting review</span></article><article><Check/><small>ACCEPTED</small><strong>{stats.accepted}</strong><span>{stats.rate===null?'No decision yet':`${stats.rate}% acceptance rate`}</span></article><article><UserRound/><small>PROFILE STRENGTH</small><strong>{stats.strength}%</strong><span>{(profile.industries||[]).length} industries selected</span></article></div><div className="rankProgress"><div><small>NEXT MILESTONE</small><strong>Get your first campaign accepted</strong></div><div className="xpBar"><i style={{width:`${Math.min(100,stats.accepted?100:Math.max(8,fires.length*20))}%`}}/></div><span>{stats.accepted?'Unlocked':'Your first real step onto the leaderboard.'}</span></div></section>}
  {tab==='info'&&<section className="accountPanel"><div className="panelHead"><div><div className="kicker"><UserRound size={14}/> MY INFO</div><h2>Your sales identity.</h2><p>This is what companies see when you fire on a deal.</p></div><button className="editBtn" onClick={()=>setEditing(!editing)}>{editing?<><Check size={15}/> Done</>:<><Pencil size={15}/> Edit profile</>}</button></div><div className="accountForm"><div className="fieldGrid two"><label>First name<input disabled={!editing} value={profile.firstName||''} onChange={e=>set('firstName',e.target.value)}/></label><label>Last name<input disabled={!editing} value={profile.lastName||''} onChange={e=>set('lastName',e.target.value)}/></label></div><div className="fieldGrid two"><label>Country<input disabled={!editing} value={profile.country||''} onChange={e=>set('country',e.target.value)}/></label><label>City<input disabled={!editing} value={profile.city||''} onChange={e=>set('city',e.target.value)}/></label></div><div className="fieldGrid two"><label>Years in sales<input disabled={!editing} type="number" value={profile.yearsExperience||''} onChange={e=>set('yearsExperience',Number(e.target.value))}/></label><label>LinkedIn<input disabled={!editing} value={profile.linkedinUrl||''} onChange={e=>set('linkedinUrl',e.target.value)}/></label></div><div className="industryField"><span>Industries</span><div className="industryChips">{INDUSTRIES.map(ind=><button disabled={!editing} type="button" key={ind} className={(profile.industries||[]).includes(ind)?'selected':''} onClick={()=>toggle(ind)}>{(profile.industries||[]).includes(ind)&&<Check size={13}/>} {ind}</button>)}</div></div><label>About your sales experience<textarea disabled={!editing} maxLength={300} value={profile.bio||''} onChange={e=>set('bio',e.target.value)}/></label>{editing&&<button className="saveProfile" onClick={save} disabled={saving}>{saving?<Loader2 className="spin" size={17}/>:<Save size={17}/>} Save changes</button>}{message&&<div className="accountMessage">{message}</div>}</div></section>}
  {tab==='deals'&&<section className="accountPanel"><div className="panelHead"><div><div className="kicker"><BriefcaseBusiness size={14}/> MY DEALS</div><h2>Everything you fired on.</h2><p>Track reviews, revisit opportunities, or withdraw when you change your mind.</p></div><div className="trackCount"><strong>{fires.length}</strong><span>active fire{fires.length===1?'':'s'}</span></div></div>{fires.length===0?<div className="emptyDeals"><Flame size={30}/><h2>No active fires.</h2><p>Go find something worth selling.</p><a href="/#opportunities">Explore opportunities <ArrowRight size={15}/></a></div>:<div className="trackList">{fires.map(f=>{const d=NAMES[f.opportunityId]||{company:f.opportunityId,title:'Sales opportunity'};return <article className="trackRow" key={f.fireId}><div className="trackFlame"><Flame size={18} fill="currentColor"/></div><div className="trackDeal"><small>{d.company}</small><strong>{d.title}</strong><span><Clock3 size={12}/> Fired {new Date(f.createdAt).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}</span></div><div className={`trackStatus ${f.status.toLowerCase()}`}>{f.status==='PENDING'?'AWAITING REVIEW':f.status.replace('_',' ')}</div><a className="trackView" href={`/opportunities/${f.opportunityId}`}>View deal <ArrowRight size={14}/></a><button className="trackLeave" onClick={()=>setConfirm(f.opportunityId)}><LogOut size={15}/> Leave</button></article>})}</div>}</section>}
  </div>{confirm&&<div className="confirmOverlay" onMouseDown={()=>setConfirm(null)}><div className="confirmBox" onMouseDown={e=>e.stopPropagation()}><div className="confirmIcon"><LogOut size={20}/></div><h2>Leave this deal?</h2><p>Your fire will be withdrawn. You can fire on this opportunity again later if slots are still available.</p><div><button onClick={()=>setConfirm(null)}>Keep my fire</button><button className="danger" disabled={leaving===confirm} onClick={()=>leave(confirm)}>{leaving===confirm?'Leaving…':'Yes, leave deal'}</button></div></div></div>}</main>
}
